stages:
  - build
  - test
  - clean

variables:
  # Ensure paths are correct for all jobs
  BIN_DIR: bin
  OBJ_DIR: obj

before_script:
  # Ensure make and gcc are available
  - apt-get update && apt-get install -y build-essential libreadline-dev

build:
  stage: build
  script:
    # Compile the project using the Makefile
    - make all
  artifacts:
    paths:
      - $BIN_DIR/
      - $OBJ_DIR/
    expire_in: 1 day

test:
  stage: test
  dependencies:
    - build
  script:
    # Run the tests
    - make test
  allow_failure: true

clean:
  stage: clean
  script:
    # Clean up build artifacts
    - make clean
  rules:
    # Only run clean on merge or manual trigger
    - if: $CI_MERGE_REQUEST_ID || $CI_PIPELINE_SOURCE == "schedule" || $CI_PIPELINE_SOURCE == "manual"
